apiVersion: apps/v1
kind: Deployment
metadata:
  name: crud-ms-node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crud-ms-node
  template:
    metadata:
      labels:
        app: crud-ms-node
    spec:
      containers:
        - name: crud-ms-node
          image: crud-ms:latest
          env:
            - name: CRUD_MS_ID
              valueFrom:
                secretKeyRef:
                  name: crud-ms-secrets
                  key: CRUD_MS_ID
            - name: CRUD_MS_SECRET
              valueFrom:
                secretKeyRef:
                  name: crud-ms-secrets
                  key: CRUD_MS_SECRET
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
