apiVersion: v1
kind: Secret
metadata:
  name: crud-ms-secrets
type: Opaque
stringData:
  CRUD_MONGO: "mongodb://admin:password@mongo:27017/popular?authSource=admin"
  CRUD_MS_ID: "123"
  CRUD_MS_SECRET: "1234"
