apiVersion: v1
kind: Secret
metadata:
  name: crud-ms-secrets
type: Opaque
stringData:
  MONGO_URI: "mongodb://mongo:lrRVqlojdFpvccFcudIcqobTjjFohcas@caboose.proxy.rlwy.net:28307"
  CRUD_MS_ID: "123"
  CRUD_MS_SECRET: "123"
